### ISSUE TITLE
Add CI/CD

### ISSUE THREAD

**Issue by QubitPi** [paion-data/packer-plugin-paion-data#1]
> [!TIP]
> 
> **Thank you for contributing!** We would like to give our warmest welcome and appreciation on your contributions to our project. 😃 
>
> Contributing to open source project is an excellent way to
>
> 1. build up your resume with real industry experience, which recruiters consider highly valuable 🥇  
> 2. learn how to build "real-life" softwares and the industry's best technology standards 🚀  
> 3. "shortcut" interview process if your are interested in joining us and working in our company 🤝 

Goal
----

CI/CD is the basis for an agile-based open source project. We want

1. Every pull request to trigger CI
2. Each merged pull request will trigger the same CI and release process (CD) on `master` branch

Steps
-----

1. [Fork](https://github.com/paion-data/packer-plugin-paion-data/fork) or clone the repository
2. Create a new branch with `git checkout -b <branch name>`
3. Create a [GitHub Action](https://github.com/features/actions) file named **ci-cd.yml** under `.github/workflows` directory with the following contents:

    ```yaml
    # Copyright Paion Data. All rights reserved.
    ---
    name: CI/CD
    
    "on":
      pull_request:
      push:
        branches:
          - master
    
    jobs:
      test-example:
        uses: ./.github/workflows/test-plugin-example.yml
    
      # referencing release.yml - get-go-version
      get-go-version:
        runs-on: ubuntu-latest
        outputs:
          go-version: ${{ steps.get-go-version.outputs.go-version }}
        steps:
          - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
          - name: 'Determine Go version'
            id: get-go-version
            run: |
              echo "Found Go $(cat .go-version)"
              echo "go-version=$(cat .go-version)" >> $GITHUB_OUTPUT

      tests:
        name: Go Tests
        needs: [test-example, get-go-version]
        outputs:
          outcome: ${{ job.status }}
        continue-on-error: true
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
            with:
              go-version: ${{ needs.get-go-version.outputs.go-version }}
          - run: |
              make build
              make test

      release:
        needs: [tests]
        if: github.ref == 'refs/heads/master'
        uses: ./.github/workflows/release.yml
    ```

7. [Create a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork). Our team will be notified automatically and start reviewing your pull request as soon as possible.
