### ISSUE TITLE
Create reusable version bump action 

### ISSUE THREAD

**Issue by QubitPi** [paion-data/packer-plugin-paion-data#3]
> [!TIP]
> 
> **Thank you for contributing!** We would like to give our warmest welcome and appreciation on your contributions to our project. 😃 
>
> Contributing to open source project is an excellent way to
>
> 1. build up your resume with real industry experience, which recruiters consider highly valuable 🥇  
> 2. learn how to build "real-life" softwares and the industry's best technology standards 🚀  
> 3. "shortcut" interview process if your are interested in joining us and working in our company 🤝 

Goal
----

This is a preparation task for https://github.com/paion-data/packer-plugin-paion-data/issues/1

Steps
-----

> [!IMPORTANT]
> This issue has a prerequisite of https://github.com/paion-data/packer-plugin-paion-data/issues/2. Make sure https://github.com/paion-data/packer-plugin-paion-data/issues/2 is **closed** before working on this issue

1. [Fork](https://github.com/paion-data/packer-plugin-paion-data/fork) or clone the repository
2. Create a new branch with `git checkout -b <branch name>`
3. Create a new file named "**version-bump.yml**" under `.github/workflows` directory with the following contents

    ```yml
    # Copyright (c) Paion Data
    # SPDX-License-Identifier: MPL-2.0
    ---
    name: Bump Version (Patch version) By GitHub Tags
    
    "on":
      workflow_call:
        inputs:
          user:
            description: The username of the GitHub user who has write access to push tags
            type: string
            required: true
          email:
            description: The emails linked to the user on GitHub
            type: string
            required: true
    
    jobs:
      bump-version:
        name: Bump Version
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - name: Download auto-version bump scripts
            run: |
              git clone https://github.com/QubitPi/hashicorp-aws.git ../hashicorp-aws
              cp ../hashicorp-aws/.github/tag-for-release.bash .github/
              cp ../hashicorp-aws/.github/upversion.py .github/
          - name: Tag for release
            run: |
              git config --global user.name ${{ inputs.user }}
              git config --global user.email ${{ inputs.email }}
              .github/tag-for-release.bash
    ```

4. [Create a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork). Our team will be notified automatically and start reviewing your pull request as soon as possible.
